### PR TITLE
Get branch up to speed/upgraded

### PR DESCRIPTION
**Pull request by andersfischernielsen**
The PR gets the `develop` branch up to speed:
- Merged working `master` into `develop`
- Updated all `package.json`s using `yarn upgrade`
- Made sure all projects still build with upgraded dependencies

### CODE REVIEW

**Comment by andersfischernielsen** [comment]
The Sass Loader error seems to be fixable by doing this: https://github.com/vuejs/vue-cli/issues/4513

**Comment by Awia00** [comment]
There seems to still be a problem with establishing connection between the client and the server. Might be due to updates to sockets?

**Comment by andersfischernielsen** [comment]
Did we upgrade to Socket.IO 2.0? I can't find anything in the dependabot mess..

**Comment by andersfischernielsen** [comment]
Apparently we did. It's 1.4.X on `master`. Getting really sick of this bot TBH

**Comment by andersfischernielsen** [comment]
Could the connection errors be ID-related? See https://socket.io/blog/socket-io-2-0-0/

**Comment by andersfischernielsen** [comment]
So, it seems that the call at https://github.com/Awia00/Pilgrims/blob/eae3326bf674e51a67f9410f3bdf6dd3ca875409/pilgrims-client/src/store/store.ts#L27 never resolves. I'm unsure what Axios does, but the `await` never resolves (also not after removing the double `await` we currently have on `develop`)

**Comment by andersfischernielsen** [comment]
After more researching, it looks like the `mongo` DB cannot be reached, that's why the Axiom call waits.

**Comment by Awia00** [comment]
Can you try with docker run -d -p 27017:27017 mongo

**Comment by Awia00** [comment]
I think the double await is there for a reason (might be something with await for the reply and awaiting the json deserialization)

**Comment by andersfischernielsen** [comment]
For some reason the `flatMap` function is missing whenever Client receives data from Server. This currently breaks the "Start Game" flow. But the connection is fine.

**Comment by andersfischernielsen** [comment]
Now Client is able to `flatMap`... Slightly annoying fix, but there's no way to hook into Socket.IO to specify a custom serializer/deserializer AFAIK

**Comment by andersfischernielsen** [comment]
Yeah, it's super strange. I think the type annotations just override whatever is actually present, which is worrying... 🙁

**Comment by andersfischernielsen** [comment]
I'm getting some weird "PIXI is missing" errors in Client now, but it builds without errors. Strange. Can you reproduce @Awia00?

**Comment by andersfischernielsen** [comment]
Woah, dependabot

**Comment by Awia00** [comment]
I'm going to merge this into master to try to get it this project moving a bit again :)

**Pull request merged**
